openapi: 3.0.4
info:
  title: AInterview API
  version: 1.0.0
paths:
  '/notice/{userId}':
    get:
      tags:
        - Notice
      summary: 특정 유저의 알림 조회
      operationId: getNoticesByUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: 알림을 조회할 유저의 ID
      responses:
        '200':
          description: 알림 리스트 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoticeListResponse'
        '400':
          description: userId 미전달
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: userId가 필요합니다.
        '500':
          description: 알림 조회 실패
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: 알림 조회 중 오류 발생
  '/notice/{userId}/{noticeId}/read':
    patch:
      tags:
        - Notice
      summary: 특정 알림 읽음 처리
      operationId: markNoticeAsRead
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: 알림 소유자의 유저 ID
        - name: noticeId
          in: path
          required: true
          schema:
            type: integer
            example: 18
          description: 읽음 처리할 알림의 ID
      responses:
        '200':
          description: 읽음 처리 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoticeReadResponse'
        '400':
          description: userId 미전달
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: userId가 필요합니다.
        '500':
          description: 읽음 처리 중 오류 발생
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: 알림 읽음 처리 중 오류 발생
  '/notice/{userId}/read':
    patch:
      tags:
        - Notice
      summary: 모든 알림 읽음 처리
      operationId: markAllNoticesAsRead
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: 모든 알림을 읽음 처리할 유저의 ID
      responses:
        '200':
          description: 모든 알림 읽음 처리 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoticeReadAllResponse'
        '400':
          description: userId 미전달
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: userId가 필요합니다.
        '500':
          description: 읽음 처리 중 오류 발생
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: 알림 읽음 처리 중 오류 발생
  /notice/push-token:
    post:
      tags:
        - Notice
      summary: 푸시 토큰 등록/업데이트
      operationId: registerPushToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushTokenRequest'
      responses:
        '200':
          description: 푸시 토큰 등록/업데이트 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PushTokenResponse'
        '400':
          description: 필수 필드 미전달
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
              examples:
                missingUserId:
                  summary: userId 미전달
                  value:
                    success: false
                    message: userId가 필요합니다.
                missingPushToken:
                  summary: pushToken 미전달
                  value:
                    success: false
                    message: pushToken이 필요합니다.
        '500':
          description: 푸시 토큰 저장 중 오류 발생
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: 푸시 토큰 저장 중 오류 발생
  /notice/send:
    post:
      tags:
        - Notice
      summary: 알림 발송
      operationId: sendNotice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendNoticeRequest'
      responses:
        '200':
          description: 알림 발송 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendNoticeResponse'
        '400':
          description: 필수 필드 미전달
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      success:
                        type: boolean
                        example: false
                      message:
                        type: string
                        example: 에러 메시지
              examples:
                missingUserId:
                  summary: userId 미전달
                  value:
                    success: false
                    message: userId가 필요합니다.
                missingTitleOrContent:
                  summary: title 또는 content 미전달
                  value:
                    success: false
                    message: title 또는 content가 필요합니다.
        '500':
          description: 알림 저장 중 오류 발생
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/paths/~1notice~1send/post/responses/400/content/application~1json/schema/allOf/0'
                  - properties:
                      message:
                        example: 알림 저장 중 오류 발생
components:
  schemas:
    Notice:
      type: object
      properties:
        notice_id:
          type: integer
          example: 1
        title:
          type: string
          example: 제목
        content:
          type: string
          example: 내용
        created_at:
          type: string
          format: date-time
          example: '2025-08-24T12:12:00.000Z'
        is_read:
          type: string
          enum:
            - 'Y'
            - 'N'
          example: 'N'
    NoticeListResponse:
      allOf:
        - $ref: '#/components/schemas/PushTokenResponse/allOf/0'
        - properties:
            message:
              example: 알림 리스트 조회 성공
            data:
              type: array
              items:
                $ref: '#/components/schemas/Notice'
    NoticeReadResponse:
      allOf:
        - $ref: '#/components/schemas/PushTokenResponse/allOf/0'
        - properties:
            message:
              example: 1 알림이 읽음 처리되었습니다.
    NoticeReadAllResponse:
      allOf:
        - $ref: '#/components/schemas/PushTokenResponse/allOf/0'
        - properties:
            message:
              example: 1 유저의 모든 알림이 읽음 처리되었습니다.
    PushTokenRequest:
      type: object
      required:
        - userId
        - pushToken
      properties:
        userId:
          type: integer
          example: 1
        pushToken:
          type: string
          example: pushToken
    PushTokenResponse:
      allOf:
        - type: object
          properties:
            success:
              type: boolean
              example: true
            message:
              type: string
              example: 성공 메시지
        - properties:
            message:
              example: 푸시 토큰이 성공적으로 저장되었습니다.
    SendNoticeRequest:
      type: object
      required:
        - userId
        - title
        - content
      properties:
        userId:
          type: integer
          example: 1
        title:
          type: string
          example: 공지사항
        content:
          type: string
          example: 새로운 기능이 추가되었습니다.
    SendNoticeResponse:
      allOf:
        - $ref: '#/components/schemas/PushTokenResponse/allOf/0'
        - properties:
            message:
              example: 알림이 전송되었습니다.
            noticeId:
              type: integer
              example: 15
