openapi: '3.0.4'
info:
  title: AInterview API
  version: '1.0.0'
paths:
  /notice/{userId}:
    $ref: './paths/notice.yaml#/~1notice~1{userId}'
  /notice/{userId}/{noticeId}/read:
    $ref: './paths/notice.yaml#/~1notice~1{userId}~1{noticeId}~1read'
  /notice/{userId}/read:
    $ref: './paths/notice.yaml#/~1notice~1{userId}~1read'
  /notice/push-token:
    $ref: './paths/notice.yaml#/~1notice~1push-token'
  /notice/send:
    $ref: './paths/notice.yaml#/~1notice~1send'

  /feedback/{userId}:
    $ref: './paths/feedback1.yaml#/~1feedback~1{userId}'
  /feedback/{userId}/{feedbackId}:
    $ref: './paths/feedback1.yaml#/~1feedback~1{userId}~1{feedbackId}'
  /feedback/{feedbackId}/{userId}:
    $ref: './paths/feedback1.yaml#/~1feedback~1{feedbackId}~1{userId}'
  /feedback/{userId}/{feedbackId}/title:
    $ref: './paths/feedback1.yaml#/~1feedback~1{userId}~1{feedbackId}~1title'
  /feedback/{userId}/{feedbackId}/memo:
    $ref: './paths/feedback1.yaml#/~1feedback~1{userId}~1{feedbackId}~1memo'
 

components:
  schemas:
    Notice:
      $ref: './schemas/notice.yaml#/Notice'
    NoticeListResponse:
      $ref: './schemas/notice.yaml#/NoticeListResponse'
    NoticeReadResponse:
      $ref: './schemas/notice.yaml#/NoticeReadResponse'
    NoticeReadAllResponse:
      $ref: './schemas/notice.yaml#/NoticeReadAllResponse'
    PushTokenRequest:
      $ref: './schemas/notice.yaml#/PushTokenRequest'
    PushTokenResponse:
      $ref: './schemas/notice.yaml#/PushTokenResponse'
    SendNoticeRequest:
      $ref: './schemas/notice.yaml#/SendNoticeRequest'
    SendNoticeResponse:
      $ref: './schemas/notice.yaml#/SendNoticeResponse'

    FeedbackSummary: { $ref: './schemas/Feedback1.yaml#/FeedbackSummary' }
    FeedbackDetail: { $ref: './schemas/Feedback1.yaml#/FeedbackDetail' }
    FeedbackListResponse: { $ref: './schemas/Feedback1.yaml#/FeedbackListResponse' }
    FeedbackDetailResponse: { $ref: './schemas/Feedback1.yaml#/FeedbackDetailResponse' }
    UpdateTitleRequest: { $ref: './schemas/Feedback1.yaml#/UpdateTitleRequest' }
    UpdateMemoRequest: { $ref: './schemas/Feedback1.yaml#/UpdateMemoRequest' }
    FeedbackTitleResponse: { $ref: './schemas/Feedback1.yaml#/FeedbackTitleResponse' }
    FeedbackMemoResponse: { $ref: './schemas/Feedback1.yaml#/FeedbackMemoResponse' }
