BaseResponse:
  type: object
  properties:
    success:
      type: boolean
      example: true
    message:
      type: string
      example: "성공 메시지"

ErrorResponse:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: "에러 메시지"